name: PrivateMines
version: 3.0-HOTFIX
main: fr.ju.privateMines.PrivateMines
api-version: 1.19
author: Julien
description: Plugin de gestion de mines privées
depend: [WorldEdit, WorldGuard, FastAsyncWorldEdit]
softdepend: [PlaceholderAPI]
commands:
  jumine:
    description: Commande principale du plugin
    aliases: [pmine, mine]
    permission: privatemines.use

permissions:
  privatemines.use:
    description: Permet d'utiliser la commande principale /jumine
    default: true
  privatemines.create:
    description: Permet de créer une mine privée
    default: true
  privatemines.delete:
    description: Permet de supprimer sa mine privée
    default: true
  privatemines.reset:
    description: Permet de réinitialiser sa mine privée
    default: true
  privatemines.expand:
    description: Permet d'agrandir sa mine privée
    default: true
  privatemines.settype:
    description: Permet de changer le type de sa mine
    default: true
  privatemines.settax:
    description: Permet de définir la taxe de sa mine
    default: true
  privatemines.teleport:
    description: Permet de se téléporter à sa mine
    default: true
  privatemines.admin:
    description: Donne accès à toutes les commandes admin
    default: op
  privatemines.admin.create:
    description: Permet de créer une mine pour un autre joueur
    default: op
  privatemines.admin.delete:
    description: Permet de supprimer la mine d'un autre joueur
    default: op
  privatemines.admin.reset:
    description: Permet de réinitialiser la mine d'un autre joueur
    default: op
  privatemines.admin.expand:
    description: Permet d'agrandir la mine d'un autre joueur
    default: op
  privatemines.admin.settype:
    description: Permet de changer le type de mine d'un autre joueur
    default: op
  privatemines.admin.settax:
    description: Permet de définir la taxe de la mine d'un autre joueur
    default: op
  privatemines.admin.settier:
    description: Permet de définir le palier d'une mine
    default: op
  privatemines.admin.pregen:
    description: Permet de pré-générer des mines
    default: op
  privatemines.admin.upgrade:
    description: Permet d'améliorer des mines (sans coût)
    default: op
  privatemines.admin.reload:
    description: Permet de recharger la configuration du plugin
    default: op
